Month 12/step 1
berezhinskiyo/algososh pull request #1
Opened 2022-11-16 22:04 UTC by berezhinskiyo

2022-11-17 04:45 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Работа проделана огромная.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. `components/ui/column/column.tsx`

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app. (App.test.tsx);

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. (Отметил несколько раз в коде, не отмечал везде, ибо было бы оч много однотипных замечаний);

  Вижу что у вас уж есть в константах тайминги, но вы их, не везде используете.

- Практически во всех алгоритмах: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма;

- Функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

- Классы, описывающие работу структур данных, вынесены в отдельные файлы в папке соответствующего компонента.

- Приложение не должно содержать `console.log` и `debugger-ов`.

- Строка:

  - У вас не правильно работает алгоритм.

    как должно быть: https://disk.yandex.ru/i/wgmcVeMhd93D4g
    как работает у вас: https://disk.yandex.ru/i/M6yeVtQV8Dim-w

- Сортировка массива:

  - У вас не оч правильно работает подсветка (Два сравниваемых числа нужно выделять цветом), во когда выбран алгоритм сортировки `выбор`.

    как у вас: https://disk.yandex.ru/i/O6Z6grGLqEMP7Q
    как должно быть: https://disk.yandex.ru/i/ALSNqY31pQl8wA

  - кнопки включения визуализации алгоритма активны, только если введены валидные данные и структура данных допускает это действие в данный момент; https://yadi.sk/d/ALSBr9GwOs6u4A

- Стек:

  - У вас странно работает выделение элемента цветом:

    как у вас: https://disk.yandex.ru/i/CDac7Lbvb1Nzxg
    как должно быть: https://disk.yandex.ru/i/tvfKPychxVIt6w

  - кнопки включения визуализации алгоритма активны, только если введены валидные данные и структура данных допускает это действие в данный момент; https://yadi.sk/d/BZkLqVyder-2Jw

  - По чек листу у `Стека` должен быть класс:

    - класс Stack с методами push, pop, clear является дженериком. Он принимает тип элементов, хранящихся в стеке. Для отображения стека в классе Stack должны быть дополнительные методы для получения данных. Например, геттеры elements и size, которые возвращают массив элементов стека и его текущий размер;

- Очередь:

  - кнопки включения визуализации алгоритма активны, только если введены валидные данные и структура данных допускает это действие в данный момент; https://yadi.sk/d/cdJhAQPFIOHtWw

  - У вас почему-то остаётся активным 2 элемент очереди: https://disk.yandex.ru/i/VlEAhISyWUbgUg. А также у вас не выделяется удаляемый элемент, и цвет выделения не тот, должен быть `#D252E1`.

  - По чек-листу: у `Очереди` должно быть класс:

    - класс Queue с методами enqueue, dequeue, clear является дженериком. Он принимает тип элементов, хранящихся в очереди. Для отображения очереди в классе Queue должны быть дополнительные методы для получения данных, например, геттеры isEmpty, elements, head и tail.

- Связный список:

  - По чек-листу: у `Связного списка` должно быть 2 класса:

    - класс `LinkedListNode` описывает элемент связного списка и хранит значение и ссылку на следующий элемент списка. Класс является дженериком, который принимает как параметр тип элемента;

    - реализован класс `LinkedList` с методами `prepend`, `append`, `addByIndex`, `deleteByIndex`, `deleteHead`, `deleteTail`и `toArray`. Класс является дженериком, который принимает как параметр тип элемента списка;

    - класс `LinkedList` должен принимать в качестве опционального параметра конструктора массив элементов для инициализации списка;

  - По чек-листу: при переходе на страницу на ней должен отображаться случайно сгенерированный список не более чем из 6 элементов;

  - кнопки включения визуализации алгоритма активны, только если введены валидные данные и структура данных допускает это действие в данный момент; https://yadi.sk/d/S3IraoucBB0yVQ

  - По нажатию на кнопку `Удалить head`, элемент должен появляться снизу, а не сверху.

  - При добавлении элемента по индексу, элемент должен выделяться зелёным цветом: https://yadi.sk/d/dZ8QgW-lXn7kEA

### **Сделает код лучше:**

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-17 04:45 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    if (n == 0) {
**Можно лучше:**

лучше всегда использовать строгое сравнение `===` и строгое неравентсво `!==`, это избавит от некоторых неявных ошибок связанных с приведением типов (например при использовании нестрогого сравнения выражение `0 == ""` вернет `true`, что не всегда ожидаемо, а выражение `0 === ""` вернет `false` т.к. типы у значений слева и справа разные, слева тип `number`, а справа тип `string`)

2022-11-17 04:45 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const fib = (n: number, memo: Record<number, number> = {}): number => {
**Надо исправить:**

По чек-листу: должна быть реализована функция getFibonacciNumbers, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи; 

А у вас она мутирует объект.

также эту функцию нужно вынести в отдельный файл utils.ts в папке этого компонента;

2022-11-17 04:45 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +        await sleep(500);
**Надо исправить:** 

Лучше использовать константу.

2022-11-17 04:45 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    if (Number.parseInt(event.currentTarget.value) < 0 || Number.parseInt(event.currentTarget.value) > 19) {
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2022-11-17 04:45 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +        <Input name="input" id="input" value={input} placeholder="Введите текст" max={19} extraClass={styles.input} type='number' isLimitText={true} onChange={handleOnChange}></Input>
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2022-11-17 04:45 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +  const [, update] = useState({});
**Можно лучше:** 

Не совсем понимаю, зачем вам тут это нужнно.

2022-11-17 04:45 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +        tmp.head = (<Circle letter={input} key='1000' state={ElementStates.Changing} isSmall={true} ></Circle>);
**Надо исправить:** 

Здесь и далее, нам не нужно задавать key. Key нужен когда мы что-то итерируем в jsx. https://ru.react.js.org/docs/lists-and-keys.html

2022-11-17 06:24 UTC, berezhinskiyo commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const fib = (n: number, memo: Record<number, number> = {}): number => {
перенес в  utils/functions/ts

2022-11-17 07:15 UTC, berezhinskiyo commented on src/components/list-page/list-page.tsx
> +  const [, update] = useState({});
это я использую для ререндера

2022-11-18 05:22 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

### **Сделает код лучше:**

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. `components/ui/column/column.tsx`

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-18 06:05 UTC, merged